name: Deploy Purescript App

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push with Podman
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          sudo podman system prune -a -f
          IMAGE_ID=$(echo $REGISTRY/$IMAGE_NAME | tr '[A-Z]' '[a-z]')

          podman build \
            --secret id=VITE_API_URL \
            -t $IMAGE_ID:latest .

          podman push $IMAGE_ID:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          passphrase: '${{ secrets.VPS_SSH_PASSPHRASE }}'
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            IMAGE_ID=$(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[A-Z]' '[a-z]')

            echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

            podman pull $IMAGE_ID:latest

            podman rmi ghcr.io/${{ github.repository }}:latest || true
            podman stop ogtool-f || true
            podman rm ogtool-f || true

            podman run -d \
              --cgroup-manager=cgroupfs \
              --name ogtool-f \
              --restart always \
              -p 4172:4172 \
              $IMAGE_ID:latest
